# Retention Policy Configuration

harbor:
  status: "ON"
  url: "http://192.168.56.60:8888"
  user: "admin"
  password: "admin"
  # cron (6필드, 초 포함)
  retention_cron: "0 0 */2 * * *"
  gc_cron: "0 0 3 * * *"
  # 프로젝트별 유지 개수 매핑
  retention_map:
    - project: "test-platform"
      keep: 3
    # 추가 필요한 경우 아래처럼 나열 가능
    # - project: "another-project"
    #   keep: 5

gitlab:
  status: "ON"
  url: "https://gitlab.com"
  private_token: "glpat-TJJeue6BU-QPFVH0apF1mmM6MQpvOjEKdTpteGx2Mg8.01.170wizixj"
  project_path: "sy0218/jsy_project"
  retention_count: 5
