# ═══════════════════════════════════════
# Server
# ═══════════════════════════════════════
SERVER_IPS=(
  "192.168.56.60"
  "192.168.56.61"
  "192.168.56.62"
)

# ═══════════════════════════════════════
# PostgreSQL
# ═══════════════════════════════════════
POSTGRES_HOST="192.168.122.59"
POSTGRES_PORT="5432"
POSTGRES_DB="job_pro"
POSTGRES_USER="sjj"
POSTGRES_PASSWORD="1234"
